# Generated by Django 5.0.3 on 2024-12-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('emp_fname', models.CharField(max_length=50)),
                ('emp_mname', models.CharField(max_length=50)),
                ('emp_lname', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_pemail', models.EmailField(max_length=254)),
                ('emp_mob_ph', models.CharField(max_length=15)),
                ('emp_off_ph', models.CharField(max_length=15)),
                ('emp_home_ph', models.CharField(max_length=15)),
                ('emp_val_from', models.DateField()),
                ('emp_val_to', models.DateField()),
                ('emp_addr', models.CharField(max_length=150)),
                ('emp_home_street', models.CharField(max_length=80)),
                ('emp_home_city', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=100)),
                ('employee_status', models.CharField(max_length=10)),
                ('emp_cp_name', models.CharField(max_length=100)),
                ('emp_cp_ph', models.CharField(max_length=15)),
                ('emp_cp_email', models.EmailField(max_length=254)),
                ('emp_cp_relation', models.CharField(max_length=100)),
                ('emp_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp_resume', models.FileField(upload_to='documents/')),
                ('emp_certif', models.FileField(upload_to='documents/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.country')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.department')),
                ('employee_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_managed', to='admin_app.employees')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.role')),
                ('sal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.salutation')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.state')),
            ],
        ),
    ]
