# Generated by Django 5.0.3 on 2025-01-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
