# Generated by Django 5.0.3 on 2025-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_employees_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
