# Generated by Django 5.0.3 on 2025-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_employees_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
