# Generated by Django 5.0.3 on 2025-01-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_employees_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emp_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
