# Generated by Django 5.0.3 on 2025-01-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_employees_emp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='emp_password',
        ),
    ]
