# Generated by Django 5.0.3 on 2025-01-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_employees_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='modified_by',
        ),
    ]
