# Generated by Django 5.0.3 on 2025-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_remove_employees_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
