# Generated by Django 5.0.3 on 2025-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_employees_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_fname',
            field=models.CharField(max_length=50, verbose_name='Employee First Name'),
        ),
    ]
