# Generated by Django 5.0.3 on 2025-01-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_employees_emp_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_lname',
            field=models.CharField(max_length=50, verbose_name='Employee Last Name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_mname',
            field=models.CharField(max_length=50, verbose_name='Employee Middle Name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_pemail',
            field=models.EmailField(max_length=254, verbose_name='Personal Email'),
        ),
    ]
