# Generated by Django 5.0.3 on 2025-01-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
