# Generated by Django 5.0.3 on 2025-01-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_holiday_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
