# Generated by Django 5.0.3 on 2025-01-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_leaverequest_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='employee',
            new_name='employee_user',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='admin_app.employees'),
        ),
    ]
