# Generated by Django 5.0.3 on 2025-01-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_rename_employee_leaverequest_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
