# Generated by Django 5.0.3 on 2025-01-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_employees_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('EL', 'Earned Leave'), ('PL', 'Parental Leave'), ('ML', 'Maternity Leave'), ('UL', 'Unpaid Leave')], default='CL', max_length=2),
        ),
    ]
