# Generated by Django 5.0.3 on 2025-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_floatingholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='floating_holidays_balance',
            field=models.IntegerField(default=2),
        ),
    ]
