# Generated by Django 5.0.3 on 2025-01-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_employees_floating_holidays_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingholiday',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
