# Generated by Django 5.0.3 on 2025-01-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_alter_floatingholiday_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloatingHoliday',
        ),
    ]
