# Generated by Django 5.0.3 on 2025-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_delete_floatingholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('year', models.IntegerField(default=2025)),
            ],
        ),
    ]
