# Generated by Django 5.0.3 on 2025-01-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_floatingholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
