# Generated by Django 5.0.3 on 2025-01-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_holiday_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
