# Generated by Django 5.0.3 on 2025-01-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_leaverequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
