# Generated by Django 5.0.3 on 2025-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_leaverequest_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='emp_total_leaves',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='emp_used_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
