# Generated by Django 5.0.3 on 2025-01-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0037_remove_leaverequest_emp_total_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emp_total_leaves',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_used_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
