# Generated by Django 5.0.3 on 2025-01-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0039_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='floating_holidays_used',
            field=models.IntegerField(default=0),
        ),
    ]
