# Generated by Django 5.0.3 on 2025-02-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_employees_floating_holidays_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
