# Generated by Django 5.0.3 on 2025-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_employees_emp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_addr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
